// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://sdobwxgvgsduoabzuhhl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNkb2J3eGd2Z3NkdW9hYnp1aGhsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjA2MjM1NTQsImV4cCI6MjA3NjE5OTU1NH0.gAU1lraiClhpIEI0x_zhnUz67C73xYUFflVYyXGoQyc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);